name: "Setup Environment"
description: "Install runtimes, package managers, and dependencies"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Enable Corepack and prepare Yarn
      shell: bash
      run: |
        corepack enable
        corepack prepare yarn@stable --activate

    - name: Cache Yarn dependencies
      uses: actions/cache@v4
      with:
        path: .yarn/cache
        key: yarn-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
        restore-keys: yarn-${{ runner.os }}-

    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Install dependencies
      shell: bash
      run: yarn install --immutable
